
init_url = "gemini://geminiprotocol.net/"

[colors]
background = [32, 32, 24]
ui         = [205, 205, 128]
text       = [205, 205, 128]
heading1   = [205, 128, 205]
heading2   = [205, 128, 205]
heading3   = [205, 128, 205]
link       = [ 64, 205, 205]
quote      = [205, 205, 205]
listitem   = [205, 205, 205]
preformat  = [100, 205, 100]
badlink    = [255,   1,   1]

[keys]
# yes/no dialog
yes                  = "y"
no                   = "n"
# navigation
move_cursor_up       = "o"
move_cursor_down     = "i"
move_page_up         = "g"
move_page_down       = "m"
cycle_to_left_tab    = "e"
cycle_to_right_tab   = "n"
inspect_under_cursor = "w"
delete_current_tab   = "v"
new_tab              = "p"
